# Generated by Django 3.0.3 on 2020-04-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bio_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=20)),
                ('Position', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=13, unique=True)),
                ('dept', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
