# Generated by Django 3.0.3 on 2020-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0002_homepage_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio_info',
            name='quotes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
