# Generated by Django 3.0.3 on 2020-04-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0004_remove_bio_info_quotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio_info',
            name='quotes',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
