# Generated by Django 3.0.3 on 2020-04-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0005_bio_info_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio_info',
            name='img',
            field=models.TextField(),
        ),
    ]
