# Generated by Django 3.0.3 on 2020-07-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bio', '0006_auto_20200422_2240'),
    ]

    operations = [
        migrations.DeleteModel(
            name='homepage_photos',
        ),
    ]
