# Generated by Django 3.0.3 on 2020-04-08 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('summary', models.TextField(default='summary mostly 200-250 words')),
                ('img_link', models.CharField(max_length=300)),
                ('blog_link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='blog_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seds_blogs.categories')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seds_blogs.blog')),
            ],
        ),
    ]
