# Generated by Django 3.0.3 on 2020-04-09 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seds_blogs.blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categories',
            name='categories',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.DeleteModel(
            name='blog_categories',
        ),
    ]
