# Generated by Django 3.0.3 on 2020-04-09 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0002_auto_20200409_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categories',
            field=models.CharField(max_length=300),
        ),
    ]
