# Generated by Django 3.0.3 on 2020-04-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0003_auto_20200409_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='seds_blogs.categories'),
            preserve_default=False,
        ),
    ]
