# Generated by Django 3.0.3 on 2020-04-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0004_auto_20200409_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
