# Generated by Django 3.0.3 on 2020-04-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0005_auto_20200409_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('summary', models.TextField(default='summary mostly 200-250 words')),
                ('img_link', models.CharField(max_length=300)),
                ('blog_link', models.CharField(max_length=300, unique=True)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
    ]
