# Generated by Django 3.0.3 on 2020-04-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0006_trending_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='video_categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='vlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('link_video', models.CharField(max_length=350)),
                ('video_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seds_blogs.video_categories')),
            ],
        ),
    ]
