# Generated by Django 3.0.3 on 2020-04-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0007_video_categories_vlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video_categories',
            old_name='categories',
            new_name='video_categories',
        ),
    ]
