# Generated by Django 3.0.3 on 2020-04-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0008_auto_20200417_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='vlog_trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('link_video', models.CharField(max_length=350)),
            ],
        ),
    ]
