# Generated by Django 3.0.3 on 2020-04-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0010_astrophotography_trending'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astrophotography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('Astrophotography_link', models.CharField(max_length=400)),
                ('summary', models.TextField(default='350 words max ', max_length=350)),
                ('date', models.DateField()),
            ],
        ),
    ]
