# Generated by Django 3.0.3 on 2020-04-22 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seds_blogs', '0011_astrophotography'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories_Astrophotography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='astrophotography',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='seds_blogs.categories_Astrophotography'),
            preserve_default=False,
        ),
    ]
